### PR TITLE
Fix vector size mistake from multi-material

### LINKED ISSUE #244: Cannot run example after pulled the updated version
Hi, I cannot run the project anymore after I pulled the updated version, it remind the segmentation faults below, and I try to delete all document and rebuild the project from kokkos, Cabana to CabanaPD, its the same note, could you tell me the possible cause of it?

wuwen@wuwenstation:~/program$ ./CabanaPD/build/install/bin/ElasticWave CabanaPD/examples/mechanics/inputs/elastic_wave.json
Kokkos::OpenMP::initialize WARNING: OMP_PROC_BIND environment variable not set
  In general, for best performance with OpenMP 4.0 or better set OMP_PROC_BIND=spread and OMP_PLACES=threads
  For best performance with OpenMP 3.1 set OMP_PROC_BIND=true
  For unit testing set OMP_PROC_BIND=false

[wuwenstation:1649069] *** Process received signal ***
[wuwenstation:1649069] Signal: Segmentation fault (11)
[wuwenstation:1649069] Signal code: Address not mapped (1)
[wuwenstation:1649069] Failing at address: (nil)
[wuwenstation:1649069] [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x45330)[0x75f6adc45330]
[wuwenstation:1649069] [ 1] ./CabanaPD/build/install/bin/ElasticWave(+0x9510b)[0x59ac3245010b]
[wuwenstation:1649069] [ 2] ./CabanaPD/build/install/bin/ElasticWave(+0x2b706)[0x59ac323e6706]
[wuwenstation:1649069] [ 3] ./CabanaPD/build/install/bin/ElasticWave(+0x18fbb)[0x59ac323d3fbb]
[wuwenstation:1649069] [ 4] /lib/x86_64-linux-gnu/libc.so.6(+0x2a1ca)[0x75f6adc2a1ca]
[wuwenstation:1649069] [ 5] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x8b)[0x75f6adc2a28b]
[wuwenstation:1649069] [ 6] ./CabanaPD/build/install/bin/ElasticWave(+0x195e5)[0x59ac323d45e5]
[wuwenstation:1649069] *** End of error message ***
Segmentation fault (core dumped)

wuwen@wuwenstation:~/program$  grep 'KOKKOS_VERSION' /home/wuwen/program/kokkos/build/install/include/KokkosCore_config.h
// KOKKOS_VERSION % 100 is the patch level
// KOKKOS_VERSION / 100 % 100 is the minor version
// KOKKOS_VERSION / 10000 is the major version
#define KOKKOS_VERSION 40100
#define KOKKOS_VERSION_MAJOR 4
#define KOKKOS_VERSION_MINOR 1
#define KOKKOS_VERSION_PATCH 0

### PR DESCRIPTION
**Pull request by streeve**
Introduced in #173 

Closes #244

### CODE REVIEW

File: src/CabanaPD_Input.hpp [hunk 1]
```diff
@@ -223,8 +223,8 @@ class Inputs
 
         // Support for multi-material: find the minimum density-bulk modulus
         // ratio for the correct critical timestep.
-        std::vector<double> rho_over_K;
         auto rho = getVector( "density" );
+        std::vector<double> rho_over_K( rho.size() );
```
Comment (pabloseleson) [inline src/CabanaPD_Input.hpp:227]: Are you just ensuring "rho_over_K" has the same size of "rho"?
